#!/usr/bin/env bash
# Displays "Best School" 10 times but on the 4th loop iteration it displays "bad luck" and on the 8th iteration it displays "good luck"
i=1
while [ $i -le 10 ]
do
	if [ $i = 4 ]; then
	echo "bad luck"
	elif [ $i = 8 ]; then
	echo "good luck"
	else
	echo "Best School"
	fi
	i=$((i+1))
done
