#!/usr/bin/env bash
# this is a script that displays numbers from 1 to 20 but displays a different thing on the 4th, 9th and 17th loop iteration which display bad luck from China, bad luck from Japan, bad luck from Italy
i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	i=$((i+1))
done
