#!/usr/bin/env bash
# script that displays to infinity and beyond indifinitely and adds something else when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
	echo"To infinity and beyond"
	sleep 2
done
